### ISSUE TITLE
Small deployment improvement suggestions

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-samples#12]
- `cds start` is deprecated and no longer provided in `@sap/cds` (only available in separate `@sap/cds-dk` package). Use `cds-serve` instead to start production server.
- Might be a good idea to specify node version in `package.json` if you don't want to always use the latest LTS version.
- You can exclude `node_modules` from `mta.tar` archive to significantly reduce its size and make deployments faster (dependencies will be automatically installed in cloud foundry anyway):
```yml
modules:
  - name: cds-ts-samples-correct-version-srv
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      # ignore "node_modules" here:
      ignore: ["node_modules/"]
    provides:
      - name: srv-api # required by consumers of CAP services (e.g. approuter)
        properties:
          srv-url: ${default-url}
    requires:
      - name: cds-ts-samples-correct-version-db
```
- You can set production server start command in `mta.yml` instead of relying on npm `start` script:
```yml
modules:
  - name: cds-ts-samples-correct-version-srv
    type: nodejs
    path: gen/srv
    parameters:
      buildpack: nodejs_buildpack
      memory: 256MB
      disk-quota: 1G
      # set start command here:
      command: node ./node_modules/@sap/cds/bin/cds-serve.js
    build-parameters:
      builder: npm
    provides:
      - name: srv-api # required by consumers of CAP services (e.g. approuter)
        properties:
          srv-url: ${default-url}
    requires:
      - name: cds-ts-samples-correct-version-db
```
This has multiple advantages:
- You can put back `cds-ts watch` as the main `start` script. No need for extra `start:ts`.
- Slightly faster startup and slightly less memory since there is no need for `npm` to be running.
- Graceful shutdown. No more `npm` swallowing termination signals sent to the application.

[More tips here](https://blogs.sap.com/2023/06/21/tips-for-running-cap-nodejs-in-sap-btp/)
